import React,{useEffect,useMemo,useState} from 'react';
import {createRoot} from 'react-dom/client';
import {supabase} from './lib/supabase';
import './styles.css';

type Any=any;
const nav=['Dashboard','Clients','Properties','Tasks','Schedules','Calendar','Workforce','Issues','Inventory','Reports'];
const colors:any={watering:'#2d8cff',deweeding:'#f2a900',fertilizing:'#45a049',mowing:'#8b5cf6',pruning:'#e45b5b',leaf_cleaning:'#16a085',pesticides:'#e83e8c',digging:'#795548',manure:'#6b4f2a',other:'#607d8b'};
const labels:any={watering:'Watering',deweeding:'De-weeding',fertilizing:'Fertilizing',mowing:'Mowing',pruning:'Pruning',leaf_cleaning:'Leaf cleaning',pesticides:'Pesticides',digging:'Digging',manure:'Manure',other:'Other'};
const empty={name:'',contact_person:'',phone:'',email:'',notes:''};
function App(){const[page,setPage]=useState('Dashboard'),[data,setData]=useState<any>({clients:[],properties:[],zones:[],tasks:[],schedules:[],notes:[],issues:[],inventory:[],messages:[],events:[]}),[client,setClient]=useState(''),[modal,setModal]=useState<Any>(null),[loading,setLoading]=useState(true);
 const load=async()=>{setLoading(true);const q=(t:string)=>supabase.from(t).select('*');const r=await Promise.all(['clients','properties','zones','tasks','maintenance_schedules','site_notes','issues','inventory_items','workforce_messages','calendar_events'].map(q));setData({clients:r[0].data||[],properties:r[1].data||[],zones:r[2].data||[],tasks:r[3].data||[],schedules:r[4].data||[],notes:r[5].data||[],issues:r[6].data||[],inventory:r[7].data||[],messages:r[8].data||[],events:r[9].data||[]});setLoading(false)};
 useEffect(()=>{load()},[]);if(loading)return <div className="center">Loading GardenOps…</div>;
 const filtered=data.clients.filter((x:any)=>!client||x.id===client);return <div className="app"><aside><div className="logo">🌿 <b>GardenOps</b></div><small>Landscaping AMC</small>{nav.map(x=><button className={'nav '+(page===x?'active':'')} onClick={()=>setPage(x)} key={x}>{x}</button>)}</aside><main><header><div><small>Landscaping AMC Operations</small><h1>{page}</h1></div><select value={client} onChange={e=>setClient(e.target.value)}><option value="">All clients</option>{data.clients.map((c:any)=><option value={c.id} key={c.id}>{c.name}</option>)}</select></header>
 {page==='Dashboard'&&<Dashboard d={data} go={setPage}/>} {page==='Clients'&&<Crud title="Clients" table="clients" rows={filtered} fields={['name','contact_person','phone','email','notes']} reload={load} newRow={empty}/>} {page==='Properties'&&<Properties d={data} reload={load}/>} {page==='Tasks'&&<Tasks d={data} reload={load}/>} {page==='Schedules'&&<Schedules d={data} reload={load}/>} {page==='Calendar'&&<Calendar d={data}/>} {page==='Workforce'&&<Workforce d={data} reload={load}/>} {page==='Issues'&&<Crud title="Issues" table="issues" rows={data.issues.filter((x:any)=>!client||x.client_id===client)} fields={['title','description','severity','status','due_at']} reload={load} newRow={{title:'',description:'',severity:'normal',status:'open',due_at:''}}/>} {page==='Inventory'&&<Inventory d={data} reload={load}/>} {page==='Reports'&&<Reports d={data}/>}</main>{modal&&<Editor {...modal} close={()=>setModal(null)} reload={load} clients={data.clients} properties={data.properties} zones={data.zones}/>}</div>}
function Dashboard({d,go}:Any){const today=d.tasks.filter((t:any)=>same(t.due_at,new Date()));const pending=d.tasks.filter((t:any)=>t.status!=='completed').length;return <><div className="stats">{[['Clients',d.clients.length],['Sites',d.properties.length],['Today',today.length],['Pending',pending],['Stock items',d.inventory.length]].map(x=><div className="card stat"><small>{x[0]}</small><strong>{x[1]}</strong></div>)}</div><div className="grid"><section className="card"><h2>Today's work</h2>{today.length?today.map((t:any)=><TaskRow t={t}/>):<Empty text="No tasks scheduled today."/>}</section><section className="card"><h2>Pending / attention</h2>{d.tasks.filter((t:any)=>t.status!=='completed').slice(0,8).map((t:any)=><TaskRow t={t}/>)}</section></div><div className="quick">{['Clients','Properties','Tasks','Schedules','Calendar','Workforce','Inventory','Reports'].map(x=><button onClick={()=>go(x)}>{x}</button>)}</div></>}
function TaskRow({t}:Any){return <div className="row"><b>{t.activity}</b><span className="tag" style={{background:colors[t.category]||colors.other}}>{labels[t.category]||t.category}</span><small>{t.status} · {t.due_at?new Date(t.due_at).toLocaleString('en-IN'):''}</small></div>}
function Properties({d,reload}:Any){return <Crud title="Properties / Sites" table="properties" rows={d.properties.filter((x:any)=>!false)} fields={['client_id','name','address','area_sqft','amc_start','amc_end','amc_value']} reload={reload} newRow={{client_id:d.clients[0]?.id||'',name:'',address:'',area_sqft:'',amc_start:'',amc_end:'',amc_value:''}} extra={(r:any)=><div className="outline"><b>Site sections</b>{d.zones.filter((z:any)=>z.property_id===r.id).map((z:any)=><span>{z.name}<small>{z.zone_type||'zone'}</small></span>)}<small>{d.zones.filter((z:any)=>z.property_id===r.id).length} sections</small></div>}/>} 
function Tasks({d,reload}:Any){return <Crud title="Maintenance Tasks" table="tasks" rows={d.tasks.filter((x:any)=>!false)} fields={['client_id','property_id','zone_id','activity','category','priority','due_at','status','instructions']} reload={reload} newRow={{client_id:d.clients[0]?.id||'',property_id:d.properties[0]?.id||'',zone_id:'',activity:'',category:'watering',priority:'normal',due_at:new Date().toISOString().slice(0,16),status:'pending',instructions:''}}/>}
function Schedules({d,reload}:Any){return <Crud title="Recurring Maintenance Schedules" table="maintenance_schedules" rows={d.schedules} fields={['client_id','property_id','zone_id','activity','category','frequency','start_date','end_date','instructions','active']} reload={reload} newRow={{client_id:d.clients[0]?.id||'',property_id:d.properties[0]?.id||'',zone_id:'',activity:'',category:'watering',frequency:'weekly',start_date:new Date().toISOString().slice(0,10),end_date:'',instructions:'',active:true}}/>}
function Workforce({d,reload}:Any){return <Crud title="Workforce Instructions & Dispatch" table="workforce_messages" rows={d.messages} fields={['client_id','property_id','audience_role','message','scheduled_for','status']} reload={reload} newRow={{client_id:d.clients[0]?.id||'',property_id:d.properties[0]?.id||'',audience_role:'gardener',message:'',scheduled_for:new Date().toISOString().slice(0,16),status:'scheduled'}}/>}
function Inventory({d,reload}:Any){return <Crud title="Inventory — Manure, Cocopeat, Potting Mix & Fertilizer" table="inventory_items" rows={d.inventory} fields={['name','category','unit','stock','minimum_stock','supplier']} reload={reload} newRow={{name:'',category:'fertilizer',unit:'kg',stock:0,minimum_stock:0,supplier:''}}/>}
function Crud({title,table,rows,fields,reload,newRow,extra}:Any){const[open,setOpen]=useState(false);const[edit,setEdit]=useState<Any>(null);return <><div className="toolbar"><button className="primary" onClick={()=>{setEdit(newRow);setOpen(true)}}>+ Add</button><span className="muted">{rows.length} records</span></div><div className="tablecard card"><table><thead><tr>{fields.slice(0,5).map((f:string)=><th>{pretty(f)}</th>)}<th>Actions</th></tr></thead><tbody>{rows.map((r:any)=><tr><td colSpan={fields.length>5?1:1}>{fields[0]==='client_id'?labelId(r[fields[0]],'clients'):String(r[fields[0]]||'—')}</td>{fields.slice(1,5).map((f:string)=><td>{f.includes('_at')||f.endsWith('date')?(r[f]?new Date(r[f]).toLocaleString('en-IN'):'—'):f==='category'?<span className="tag" style={{background:colors[r[f]]||colors.other}}>{labels[r[f]]||r[f]}</span>:String(r[f]??'—')}</td>)}<td><button className="smallbtn" onClick={()=>{setEdit(r);setOpen(true)}}>Edit</button><button className="smallbtn danger" onClick={async()=>{if(confirm('Delete this record?')){await supabase.from(table).delete().eq('id',r.id);reload()}}}>Delete</button></td></tr>)}</tbody></table>{!rows.length&&<Empty text="No records yet. Add the first one above."/>}</div>{open&&<Editor title={title} table={table} row={edit} close={()=>setOpen(false)} reload={()=>{setOpen(false);reload()}} fields={fields}/>} {extra&&rows.slice(0,3).map(extra)}</>}
function Editor({title,table,row,close,reload,fields,clients=[],properties=[],zones=[]}:Any){const[f,setF]=useState({...row});const save=async(e:any)=>{e.preventDefault();const clean:any={...f};Object.keys(clean).forEach(k=>{if(clean[k]==='')clean[k]=null});if(!clean.company_id)delete clean.company_id;const res=f.id?await supabase.from(table).update(clean).eq('id',f.id):await supabase.from(table).insert(clean);if(res.error)alert(res.error.message);else reload()};return <div className="overlay"><div className="modal"><div className="between"><h2>{f.id?'Edit':'Add'} {title}</h2><button onClick={close}>×</button></div><form onSubmit={save}>{fields.map((key:string)=>{if(key==='client_id')return <label>Client<select value={f[key]||''} onChange={e=>setF({...f,[key]:e.target.value})}><option value="">Select</option>{clients.map((x:any)=><option value={x.id}>{x.name}</option>)}</select></label>;if(key==='property_id')return <label>Property<select value={f[key]||''} onChange={e=>setF({...f,[key]:e.target.value})}><option value="">Select</option>{properties.map((x:any)=><option value={x.id}>{x.name}</option>)}</select></label>;if(key==='zone_id')return <label>Zone<select value={f[key]||''} onChange={e=>setF({...f,[key]:e.target.value})}><option value="">None</option>{zones.map((x:any)=><option value={x.id}>{x.name}</option>)}</select></label>;if(key==='category')return <label>Task type<select value={f[key]||'other'} onChange={e=>setF({...f,[key]:e.target.value})}>{Object.keys(labels).map(x=><option value={x}>{labels[x]}</option>)}</select></label>;if(key==='status')return <label>Status<select value={f[key]||'pending'} onChange={e=>setF({...f,[key]:e.target.value})}>{['pending','in_progress','completed','overdue','cancelled','open','scheduled','sent'].map(x=><option>{x}</option>)}</select></label>;if(key==='active')return <label>Active<input type="checkbox" checked={!!f[key]} onChange={e=>setF({...f,[key]:e.target.checked})}/></label>;if(key.includes('_at'))return <label>{pretty(key)}<input type="datetime-local" value={f[key]?String(f[key]).slice(0,16):''} onChange={e=>setF({...f,[key]:e.target.value})}/></label>;if(key.endsWith('date'))return <label>{pretty(key)}<input type="date" value={f[key]||''} onChange={e=>setF({...f,[key]:e.target.value})}/></label>;if(key==='description'||key==='instructions'||key==='notes'||key==='message')return <label>{pretty(key)}<textarea value={f[key]||''} onChange={e=>setF({...f,[key]:e.target.value})}/></label>;return <label>{pretty(key)}<input type={['area_sqft','amc_value','stock','minimum_stock'].includes(key)?'number':'text'} value={f[key]??''} onChange={e=>setF({...f,[key]:e.target.value})}/></label>})}<button className="primary">Save changes</button></form></div></div>}
function Calendar({d}:Any){const[start,setStart]=useState(new Date());const days=Array.from({length:35},(_,i)=>{const x=new Date(start);x.setDate(x.getDate()-x.getDay()+i);return x});const events=d.tasks.map((t:any)=>({...t,kind:'task'})).concat(d.events.map((e:any)=>({...e,kind:'event',activity:e.title,category:e.event_type||'other',due_at:e.starts_at})));return <div className="card"><div className="between"><div><h2>Maintenance Calendar</h2><small>Task colours: watering, de-weeding, fertilizing, mowing, pruning and more</small></div><div><button className="smallbtn" onClick={()=>setStart(new Date(start.getFullYear(),start.getMonth(),start.getDate()-35))}>‹</button><button className="smallbtn" onClick={()=>setStart(new Date())}>Today</button><button className="smallbtn" onClick={()=>setStart(new Date(start.getFullYear(),start.getMonth(),start.getDate()+35))}>›</button></div></div><div className="legend">{Object.keys(labels).slice(0,9).map(x=><span><i style={{background:colors[x]}}></i>{labels[x]}</span>)}</div><div className="calgrid">{days.map(day=><div className="calday"><b>{day.getDate()} {day.toLocaleDateString('en-IN',{month:'short'})}</b>{events.filter((e:any)=>same(e.due_at,day)).map((e:any)=><div className="calevent" style={{background:colors[e.category]||colors.other}}>{e.activity}</div>)}</div>)}</div></div>}
function Reports({d}:Any){const[range,setRange]=useState(7);const end=new Date(),start=new Date(end);start.setDate(end.getDate()-range+1);const all=d.tasks.filter((t:any)=>new Date(t.due_at)>=start&&new Date(t.due_at)<=end);const done=all.filter((t:any)=>t.status==='completed'),pending=all.length-done.length;const by:any={};all.forEach((t:any)=>by[t.category]=(by[t.category]||{done:0,total:0}));all.forEach((t:any)=>{by[t.category].total++;if(t.status==='completed')by[t.category].done++});return <><div className="toolbar"><button className={range===1?'primary':''} onClick={()=>setRange(1)}>Daily</button><button className={range===7?'primary':''} onClick={()=>setRange(7)}>Weekly</button><button className={range===30?'primary':''} onClick={()=>setRange(30)}>Monthly</button></div><div className="stats"><div className="card stat"><small>Scheduled</small><strong>{all.length}</strong></div><div className="card stat"><small>Completed</small><strong>{done.length}</strong></div><div className="card stat"><small>Pending</small><strong>{pending}</strong></div><div className="card stat"><small>Completion</small><strong>{all.length?Math.round(done.length/all.length*100):0}%</strong></div></div><div className="card"><h2>Current work status</h2>{Object.entries(by).map(([k,v]:Any)=><div className="reportrow"><b>{labels[k]||k}</b><span>{v.done}/{v.total}</span><div className="bar"><i style={{width:(v.total?v.done/v.total*100:0)+'%',background:colors[k]||colors.other}}/></div><small>{v.total?Math.round(v.done/v.total*100):0}% complete</small></div>)}{!all.length&&<Empty text="No scheduled work in this period."/>}</div></>}
function labelId(id:string,table:string){return id||'—'}function pretty(s:string){return s.replaceAll('_',' ').replace(/\b\w/g,x=>x.toUpperCase())}function same(a:any,b:Date){return a&&new Date(a).toDateString()===b.toDateString()}const Empty=({text}:{text:string})=><div className="empty">{text}</div>;
createRoot(document.getElementById('root')!).render(<App/>);
